---
# tasks file for sbaerlocher.iptables

- name: add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: install iptables
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - "{{ iptables_packages }}"
  notify:
    - start iptables
    - enable iptables
    - start ip6tables
    - enable ip6tables
  tags:
    - configuration

- name: template iptables
  become: true
  template:
    src: iptables.j2
    dest: "{{ iptables_configuration }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart iptables
  tags:
    - configuration

- name: template ip6tables
  become: true
  template:
    src: ip6tables.j2
    dest: "{{ iptables6_configuration }}"
    owner: root
    group: root
    mode: 0600
  notify: restart ip6tables
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"
  tags:
    - configuration
