---
# tasks file for sbaerlocher.iptables

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"

- name: install iptables
  package: name={{ item }} state=installed
  with_items: "{{ iptables_packages }}"

- name: template iptables
  template: >
      src=iptables.j2
      dest=/etc/sysconfig/iptables
      owner=root
      group=root
      mode=0600
  notify: restart iptables

- name: template ip6tables
  template: >
      src=ip6tables.j2
      dest=/etc/sysconfig/ip6tables
      owner=root
      group=root
      mode=0600
  notify: restart ip6tables
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"

- name: enable and start iptables service
  service: name=iptables state=started enabled=yes

- name: enable and start ip6tables service
  service: name=ip6tables state=started enabled=yes
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"#