---
# handlers file for sbaerlocher.iptables

- name: restart iptables
  become: true
  service:
    name: "{{ iptables_service }}"
    state: restarted

- name: start iptables
  become: true
  service:
    name: "{{ iptables_service }}"
    state: started

- name: enable iptables
  become: true
  service:
    name: "{{ iptables_service }}"
    enabled: true

- name: restart ip6tables
  become: true
  service:
    name: "{{ ip6tables_service }}"
    state: restarted

- name: start ip6tables
  become: true
  service:
    name: "{{ ip6tables_service }}"
    state: started
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"

- name: enable ip6tables
  become: true
  service:
    name: "{{ ip6tables_service }}"
    enabled: true
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"
